#!/usr/bin/env python3
"""Generate a sample ETF reference guide PDF and send it to Telegram."""

from __future__ import annotations

import os
import sys
from pathlib import Path
import requests

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

# Add scripts directory to path to load config
SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from telegram_notify import load_config


def build_pdf(output_path: str) -> None:
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#1A365D"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "DocSubTitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#4A5568"),
        spaceAfter=12,
    )
    section_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#2B6CB0"),
        spaceBefore=10,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor("#2D3748"),
    )
    bold_body = ParagraphStyle(
        "BoldBody",
        parent=body_style,
        fontName="Helvetica-Bold",
    )
    callout_style = ParagraphStyle(
        "Callout",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor("#1A202C"),
    )

    story = []

    # Title & Subtitle
    story.append(Paragraph("📊 achiOS Core ETF Reference Guide", title_style))
    story.append(Paragraph("A quick-reference sheet for long-term compound investing • Generated by achiOS", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#2B6CB0"), spaceAfter=10))

    # Section 1: Core ETF Comparison Table
    story.append(Paragraph("1. Core ETF Comparison", section_style))
    
    table_data = [
        [
            Paragraph("<b>Ticker</b>", bold_body),
            Paragraph("<b>Fund Name</b>", bold_body),
            Paragraph("<b>Benchmark</b>", bold_body),
            Paragraph("<b>Expense Ratio</b>", bold_body),
            Paragraph("<b>Yield</b>", bold_body),
            Paragraph("<b>Role in Portfolio</b>", bold_body),
        ],
        [
            Paragraph("<b>VOO</b>", bold_body),
            Paragraph("Vanguard S&P 500 ETF", body_style),
            Paragraph("S&P 500 Index (503 Large-Cap US)", body_style),
            Paragraph("0.03%", body_style),
            Paragraph("~1.30%", body_style),
            Paragraph("US Core Foundation (~60-70%)", body_style),
        ],
        [
            Paragraph("<b>VXUS</b>", bold_body),
            Paragraph("Vanguard Total International", body_style),
            Paragraph("Global Ex-US (~8,000 stocks)", body_style),
            Paragraph("0.07%", body_style),
            Paragraph("~3.10%", body_style),
            Paragraph("Global Diversification (~15-20%)", body_style),
        ],
        [
            Paragraph("<b>QQQM</b>", bold_body),
            Paragraph("Invesco NASDAQ 100", body_style),
            Paragraph("NASDAQ 100 (Non-financial large tech)", body_style),
            Paragraph("0.15%", body_style),
            Paragraph("~0.60%", body_style),
            Paragraph("Tech Growth Tilt (~10-15%)", body_style),
        ],
    ]

    t = Table(table_data, colWidths=[0.75 * inch, 1.8 * inch, 1.9 * inch, 0.9 * inch, 0.65 * inch, 1.5 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#EDF2F7")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")]),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))

    # Section 2: Dollar-Cost Averaging (DCA) Strategy
    story.append(Paragraph("2. Dollar-Cost Averaging (DCA) Principles", section_style))
    dca_text = (
        "<b>What is DCA?</b> Dollar-Cost Averaging is the practice of investing a fixed dollar amount "
        "at recurring intervals (e.g. monthly on payday), regardless of asset price fluctuations.<br/>"
        "• <b>Automatic Dip-Buying:</b> When market prices decline, your fixed allocation automatically buys more shares.<br/>"
        "• <b>Emotionless Execution:</b> Eliminates the friction of market timing, FOMO, or panic selling.<br/>"
        "• <b>Cash Flow Alignment:</b> Matches personal recurring income directly to long-term compound asset accumulation."
    )
    story.append(Paragraph(dca_text, body_style))
    story.append(Spacer(1, 8))

    # Section 3: Portfolio Rules of Thumb
    story.append(Paragraph("3. Core Allocation Guidelines", section_style))
    rules_text = (
        "1. <b>Low Fees Win:</b> Keep weighted portfolio expense ratio below 0.10%.<br/>"
        "2. <b>Long-Term Horizon:</b> Index funds compound over 5+ year timeframes; short-term volatility is noise.<br/>"
        "3. <b>Automate Everything:</b> Set up recurring notifications and scheduled reports to stay informed without active trading stress."
    )
    story.append(Paragraph(rules_text, body_style))
    story.append(Spacer(1, 10))

    # Footer note callout box
    callout_data = [[
        Paragraph(
            "<b>💡 achiOS Operating Principle:</b> <i>\"Time in the market beats timing the market.\"</i> "
            "Track daily metrics via your automated Telegram alerts at 04:30 AM & 08:00 AM Manila.",
            callout_style
        )
    ]]
    callout_table = Table(callout_data, colWidths=[7.5 * inch])
    callout_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#EBF8FF")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#3182CE")),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ]))
    story.append(callout_table)

    doc.build(story)


def send_pdf_to_telegram(pdf_path: str, caption: str) -> None:
    token, chat_id = load_config()
    url = f"https://api.telegram.org/bot{token}/sendDocument"

    with open(pdf_path, "rb") as f:
        response = requests.post(
            url,
            data={"chat_id": chat_id, "caption": caption},
            files={"document": f},
            timeout=30,
        )
    if not response.ok:
        raise SystemExit(f"Telegram upload failed: {response.status_code} {response.text}")
    print("PDF successfully delivered to Telegram!")


def main() -> int:
    output_dir = Path.home() / ".local" / "state" / "achios"
    output_dir.mkdir(parents=True, exist_ok=True)
    pdf_file = output_dir / "achiOS_ETF_Reference_Guide.pdf"

    print(f"Generating PDF at {pdf_file}...")
    build_pdf(str(pdf_file))
    print(f"File generated ({pdf_file.stat().st_size} bytes). Sending to Telegram...")
    send_pdf_to_telegram(str(pdf_file), "📄 Here is your sample achiOS ETF Reference Guide (PDF)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
