#!/usr/bin/env python3
"""Install achiOS personas as global Codex and Claude Code agents."""
from __future__ import annotations

import argparse
import json
import re
import tomllib
from pathlib import Path
from uuid import uuid4

ROOT = Path(__file__).resolve().parent.parent
MARKER = "Generated by achiOS install_portable_agents.py"
CODEX_MODEL = "gpt-6.1-sol"
CLAUDE_MODEL = "claude-sonnet-5-5"
TARGETS = {"codex": ".codex/agents", "claude": ".claude/agents"}


def prompt(name: str, skills: list[str]) -> str:
    body = (ROOT / "agents" / f"{name}.md").read_text().strip()
    return body + "\n\nSuggested skills: " + ", ".join(skills) + ".\n" + (
        "These are starting points. Discover and invoke any other installed skill "
        "when it fits the task. Read the selected skill before using it. "
        "Resolve paths on the current host and follow the current repository's instructions. "
        "Use achios-google for account-scoped Google access from any repository. "
        "Apply unslop and humanizer to authored prose.\n"
    )


def render(name: str, entry: dict, target: str) -> str:
    body = prompt(name, entry["skills"])
    if target == "codex":
        fields = {"name": name, "description": entry["description"],
                  "developer_instructions": body}
        return f"# {MARKER}\n" + "".join(
            f"{key} = {json.dumps(value, ensure_ascii=False)}\n" for key, value in fields.items()
        )
    fields = {"name": name, "description": entry["description"],
              "model": CLAUDE_MODEL, "effort": "high"}
    return "---\n" + "".join(
        f"{key}: {json.dumps(value, ensure_ascii=False)}\n" for key, value in fields.items()
    ) + f"---\n<!-- {MARKER} -->\n\n{body}"


def codex_defaults(text: str) -> str:
    """Update only the two subagent defaults, preserving other TOML settings."""
    current = tomllib.loads(text)
    lines = text.splitlines(keepends=True)
    start = next((i for i, line in enumerate(lines)
                  if re.fullmatch(r"\s*\[agents\]\s*(?:#.*)?\n?", line)), None)
    if start is None:
        if "agents" in current:
            raise ValueError("Codex agents settings need an [agents] table; config left intact")
        lines = [(text.rstrip() + "\n\n") if text.strip() else "", "[agents]\n"]
        start = len(lines) - 1
    end = next((i for i in range(start + 1, len(lines))
                if re.match(r"\s*\[", lines[i])), len(lines))
    block = lines[start + 1:end]
    for key, value in (("default_subagent_model", CODEX_MODEL),
                       ("default_subagent_reasoning_effort", "medium")):
        setting = f"{key} = {json.dumps(value)}\n"
        index = next((i for i, line in enumerate(block)
                      if re.match(rf"\s*{key}\s*=", line)), None)
        if index is None:
            if block and not block[-1].endswith("\n"):
                block[-1] += "\n"
            block.append(setting)
        else:
            block[index] = setting
    if not lines[start].endswith("\n"):
        lines[start] += "\n"
    lines[start + 1:end] = block
    result = "".join(lines)
    parsed = tomllib.loads(result)["agents"]
    if (parsed.get("default_subagent_model") != CODEX_MODEL
            or parsed.get("default_subagent_reasoning_effort") != "medium"):
        raise ValueError("Could not set Codex subagent defaults")
    return result


def install(home: Path, targets: list[str], *, dry_run: bool = False) -> list[dict]:
    registry = json.loads((ROOT / "config/portable-agents.json").read_text())
    writes = []
    for target in dict.fromkeys(targets):
        for name, entry in registry.items():
            if not re.fullmatch(r"[a-z][a-z0-9-]*", name):
                raise ValueError(f"Invalid agent name: {name}")
            extension = "toml" if target == "codex" else "md"
            path = home / TARGETS[target] / f"{name}.{extension}"
            content = render(name, entry, target)
            if path.is_symlink() or (path.exists() and (
                    not path.is_file() or MARKER not in path.read_text())):
                raise ValueError(f"Existing agent left intact: {path}")
            writes.append((path, content))
    if "codex" in targets:
        config = home / ".codex/config.toml"
        text = config.read_text() if config.exists() else ""
        writes.append((config, codex_defaults(text)))
    receipt = []
    for path, content in writes:
        present = path.exists()
        old = path.read_text() if present else None
        status = "present" if old == content else "planned" if dry_run else "updated" if present else "created"
        backup = None
        if not dry_run and old != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            if present:
                backup = path.with_name(path.name + f".achios-{uuid4().hex}.bak")
                backup.write_text(old)
                backup.chmod(path.stat().st_mode & 0o777)
            path.write_text(content)
        receipt.append({"path": str(path), "status": status, "backup": str(backup) if backup else None})
    return receipt


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=TARGETS, action="append")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    try:
        print(json.dumps({"agents": install(Path.home(), args.target or list(TARGETS),
                                           dry_run=args.dry_run)}))
        return 0
    except (OSError, ValueError) as exc:
        print(json.dumps({"error": str(exc)}))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
